'use client';

import { useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import { useAuth } from '@/context/AuthContext';
import { UploadCloud, FileVideo, Film, X, Image as ImageIcon, Settings, ChevronDown, Coins, ShieldCheck, Send } from 'lucide-react';

export default function AdminUploadPage() {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('Entertainment');
  const [price, setPrice] = useState<number | ''>(0);
  const [status, setStatus] = useState<'published' | 'draft'>('published');
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [progress, setProgress] = useState(0);
  const { user } = useAuth();
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleUpload = async (e?: React.FormEvent, isDraft = false) => {
    if (e) e.preventDefault();
    if (!file || !title || !user) {
      alert('Please provide a file and a title.');
      return;
    }
    if (file.size > 500 * 1024 * 1024) { // 500MB client-side check
      alert('File is too large. Maximum size is 500MB.');
      return;
    }

    setUploading(true);
    try {
      const videoId = crypto.randomUUID();
      const cloudName = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
      const uploadPreset = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;

      if (!cloudName || !uploadPreset) {
        alert('Cloudinary environment variables are missing.');
        setUploading(false);
        return;
      }

      const url = `https://api.cloudinary.com/v1_1/${cloudName}/video/upload`;
      const formData = new FormData();
      formData.append('file', file);
      formData.append('upload_preset', uploadPreset);
      formData.append('public_id', videoId);

      const xhr = new XMLHttpRequest();
      xhr.open('POST', url, true);

      xhr.upload.onprogress = (e) => {
        if (e.lengthComputable) setProgress((e.loaded / e.total) * 100);
      };

      xhr.onload = async () => {
        if (xhr.status === 200) {
          const response = JSON.parse(xhr.responseText);
          const videoUrl = response.secure_url;
          const cloudinaryPublicId = response.public_id;
          const thumbnailUrl = videoUrl.replace(/\.[^/.]+$/, ".jpg"); // Derive thumbnail auto-generated by Cloudinary

          await setDoc(doc(db, 'videos', videoId), {
            id: videoId,
            title,
            description,
            category,
            videoUrl,
            thumbnailUrl,
            cloudinaryPublicId,
            uploaderId: user.uid,
            price: Number(price) || 0,
            isFree: Number(price) === 0,
            views: 0,
            likes: 0,
            status: isDraft ? 'draft' : status,
            createdAt: serverTimestamp(),
            updatedAt: serverTimestamp()
          });
          setUploading(false);
          router.push('/browse');
        } else {
          console.error('Upload failed:', xhr.responseText);
          alert('Upload failed. Check console.');
          setUploading(false);
        }
      };

      xhr.onerror = () => { alert('Network error occurred.'); setUploading(false); };
      xhr.send(formData);
    } catch (error) {
      console.error('Error in upload process:', error);
      setUploading(false);
    }
  };

  return (
    <div className="bg-slate-50 dark:bg-gray-950 text-slate-900 dark:text-slate-100 min-h-screen flex items-center justify-center p-4 md:p-8 font-sans">
      <div className="max-w-5xl w-full bg-white dark:bg-[#191022] border border-slate-200 dark:border-purple-600/20 shadow-2xl rounded-xl overflow-hidden flex flex-col">

        <header className="flex items-center justify-between px-8 py-5 border-b border-slate-200 dark:border-purple-600/10">
          <div className="flex items-center gap-3">
            <div className="bg-purple-600 p-2 rounded-lg">
              <Film className="text-white w-6 h-6" />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-tight">Upload Content</h1>
              <p className="text-sm text-slate-500 dark:text-slate-400">Ready to share your masterpiece?</p>
            </div>
          </div>
          <button onClick={() => router.back()} className="p-2 hover:bg-slate-200 dark:hover:bg-purple-600/20 rounded-full transition-colors">
            <X className="w-5 h-5" />
          </button>
        </header>

        <div className="flex-1 overflow-y-auto p-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">

            {/* Left Column */}
            <div className="lg:col-span-7 space-y-8">
              <section>
                <label className="block text-sm font-semibold mb-3 uppercase tracking-wider text-purple-600">1. Video File</label>
                <div onClick={() => fileInputRef.current?.click()} className="group relative flex flex-col items-center justify-center border-2 border-dashed border-slate-300 dark:border-purple-600/30 rounded-xl p-12 bg-slate-100 dark:bg-purple-600/5 hover:border-purple-600 transition-all cursor-pointer">
                  <div className="size-16 rounded-full bg-purple-600/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                    <UploadCloud className="text-purple-600 w-8 h-8" />
                  </div>
                  <h3 className="text-lg font-bold mb-1">{file ? file.name : 'Drag & drop video files'}</h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 mb-6 text-center">MP4, MOV, or AVI up to 500MB. <br />High resolution recommended.</p>
                  <button type="button" className="bg-purple-600 hover:bg-purple-600/90 text-white px-6 py-2.5 rounded-lg font-bold transition-colors shadow-lg shadow-purple-600/20">Select File</button>
                  <input ref={fileInputRef} type="file" accept="video/*" onChange={(e) => setFile(e.target.files?.[0] || null)} className="hidden" />
                </div>
                {uploading && (
                  <div className="w-full bg-gray-800 rounded-full h-2.5 mt-4 overflow-hidden">
                    <div className="bg-purple-600 h-2.5 rounded-full transition-all duration-300" style={{ width: `${progress}%` }}></div>
                    <p className="text-xs text-purple-400 mt-2 text-center">Uploading... {Math.round(progress)}%</p>
                  </div>
                )}
              </section>

              <section>
                <label className="block text-sm font-semibold mb-3 uppercase tracking-wider text-purple-600">2. Thumbnail</label>
                <div className="grid grid-cols-3 gap-4">
                  <div className="col-span-2 relative aspect-video bg-slate-200 dark:bg-purple-600/10 rounded-lg border border-slate-300 dark:border-purple-600/20 flex flex-col items-center justify-center overflow-hidden">
                    <ImageIcon className="w-10 h-10 text-slate-400 dark:text-slate-600" />
                    <p className="text-xs text-slate-500 mt-2 font-medium">Auto-generated by Cloudinary</p>
                  </div>
                </div>
              </section>

              <section className="bg-slate-100 dark:bg-purple-600/5 p-6 rounded-xl border border-slate-200 dark:border-purple-600/10">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="font-bold flex items-center gap-2"><Settings className="text-purple-600 w-5 h-5" /> Advanced Settings</h3>
                </div>
                <div className="grid grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium">Make Public</span>
                      <input type="checkbox" checked={status === 'published'} onChange={(e) => setStatus(e.target.checked ? 'published' : 'draft')} className="rounded border-purple-600 text-purple-600 focus:ring-purple-600 bg-transparent w-4 h-4" />
                    </div>
                  </div>
                </div>
              </section>
            </div>

            {/* Right Column */}
            <div className="lg:col-span-5 space-y-6">
              <section className="space-y-5">
                <label className="block text-sm font-semibold uppercase tracking-wider text-purple-600">3. Metadata Details</label>
                <div className="space-y-1.5">
                  <span className="text-xs font-bold text-slate-600 dark:text-slate-400 ml-1">Title</span>
                  <input type="text" required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. My Cinematic Masterpiece" className="w-full bg-slate-100 dark:bg-gray-900 border border-slate-300 dark:border-purple-600/20 rounded-lg p-3 focus:ring-2 focus:ring-purple-600 outline-none transition-all" />
                </div>
                <div className="space-y-1.5">
                  <span className="text-xs font-bold text-slate-600 dark:text-slate-400 ml-1">Category</span>
                  <div className="relative">
                    <select value={category} onChange={(e) => setCategory(e.target.value)} className="w-full appearance-none bg-slate-100 dark:bg-gray-900 border border-slate-300 dark:border-purple-600/20 rounded-lg p-3 focus:ring-2 focus:ring-purple-600 outline-none pr-10">
                      <option value="Entertainment">Entertainment</option>
                      <option value="Education">Education</option>
                      <option value="Gaming">Gaming</option>
                      <option value="Technology">Technology</option>
                    </select>
                    <ChevronDown className="absolute right-3 top-3 pointer-events-none text-slate-400 w-5 h-5" />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <span className="text-xs font-bold text-slate-600 dark:text-slate-400 ml-1">Description</span>
                  <textarea required value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Tell viewers about your video..." rows={4} className="w-full bg-slate-100 dark:bg-gray-900 border border-slate-300 dark:border-purple-600/20 rounded-lg p-3 focus:ring-2 focus:ring-purple-600 outline-none resize-none"></textarea>
                </div>
              </section>

              <section className="bg-purple-600/10 dark:bg-purple-600/5 p-6 rounded-xl border border-purple-600/20">
                <label className="block text-sm font-semibold uppercase tracking-wider text-purple-600 mb-4">4. Monetization</label>
                <div className="flex items-center gap-4">
                  <div className="flex-1 space-y-1.5">
                    <span className="text-xs font-bold text-slate-600 dark:text-slate-400 ml-1">Price in Coins</span>
                    <div className="relative">
                      <input type="number" min="0" value={price === '' ? '' : price} onChange={(e) => setPrice(e.target.value === '' ? '' : Number(e.target.value))} className="w-full bg-slate-50 dark:bg-gray-900 border border-slate-300 dark:border-purple-600/20 rounded-lg p-3 pl-10 focus:ring-2 focus:ring-purple-600 outline-none" />
                      <Coins className="absolute left-3 top-3 text-amber-500 w-5 h-5" />
                    </div>
                  </div>
                  <div className="pt-6">
                    <p className="text-[10px] text-slate-500 italic max-w-[120px]">Keep at 0 for free content available to all.</p>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>

        <footer className="px-8 py-5 border-t border-slate-200 dark:border-purple-600/10 bg-slate-50 dark:bg-gray-950 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-xs text-slate-500">
            <ShieldCheck className="w-4 h-4" /> Uploaded files are scanned for safety.
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={() => handleUpload(undefined, true)}
              disabled={uploading || !file}
              className="px-6 py-2.5 rounded-lg border border-slate-300 dark:border-purple-600/30 font-bold hover:bg-slate-200 dark:hover:bg-purple-600/10 transition-colors disabled:opacity-50"
            >
              Save Draft
            </button>
            <button
              onClick={(e) => handleUpload(e, false)}
              disabled={uploading || !file}
              className="px-8 py-2.5 rounded-lg bg-purple-600 hover:bg-purple-600/90 text-white font-bold transition-all shadow-lg shadow-purple-600/30 flex items-center gap-2 disabled:opacity-50"
            >
              {uploading ? 'Processing...' : 'Submit for Approval'}
              {!uploading && <Send className="w-4 h-4" />}
            </button>
          </div>
        </footer>

      </div>
    </div>
  );
}